# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8ead6619ba83cc34f1f5eed34be2fde5eb62bded9e58ed5653712bd211a2cbe80fc87f8ec2ed1b56ac13fdd65f807cb9e5d0a0b92129fdda4384bb2cf7d89d1d

test:
  secret_key_base: 0fbea0012b11e4feba68fd5ecd6909b49fb42df770f8330c7e15df5cc693954ebb029b2a99eb1a65259e0636b0f3fa63db4b5436b0e0d8ca52ebf7a2b1d17fa9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
